### ISSUE TITLE
 Add fallback to `any` / `unknown`  in case of errors in generating `.d.ts`

### ISSUE THREAD

**Issue by vvscode** [KuveytTurk/react-dts-generator#2]
@KuveytTurk

In some cases, the generator fails with errors. Looks like it worth to add a fallback to `any` type in such cases

**Comment by vvscode** [comment]
@mozkarakoc will you adopt such MR?

**Comment by mozkarakoc** [comment]
The generator [returns](https://github.com/KuveytTurk/react-dts-generator/blob/master/src/utils.ts#L11-L25) `any` for undefined props. Could you provide more detailed sample input and expected output?

**Comment by vvscode** [comment]
`./Feedback.js`
https://gist.github.com/vvscode/be98fb5072b498172913e3703edb7e16

```js
const { generate }  = require('react-dts-generator');
const result = generate({
  input: './Feedback.js',
	isBaseClass: true,
});

console.log(result);
```

gives me 

```~/r/docgen-issue [1]> node index.js
/Users/vvscode/repo/docgen-issue/node_modules/react-dts-generator/bin/src/utils.js:67
        values.forEach(item => unions += `${item.value} | `);
               ^

TypeError: values.forEach is not a function
    at generateOneOf (/Users/vvscode/repo/docgen-issue/node_modules/react-dts-generator/bin/src/utils.js:67:16)
    at Object.generateProp (/Users/vvscode/repo/docgen-issue/node_modules/react-dts-generator/bin/src/utils.js:137:29)
    at /Users/vvscode/repo/docgen-issue/node_modules/react-dts-generator/bin/src/index.js:44:46
    at Array.forEach (<anonymous>)
    at generate (/Users/vvscode/repo/docgen-issue/node_modules/react-dts-generator/bin/src/index.js:39:22)
    at Object.<anonymous> (/Users/vvscode/repo/docgen-issue/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)```

**Comment by vvscode** [comment]
I'm ready to provide a PR with tests and so on. Just wondering if you're fine about it

**Comment by mozkarakoc** [comment]
It seems a nice feature. PR's are always welcome.

**Comment by vvscode** [comment]
https://github.com/KuveytTurk/react-dts-generator/issues/2

**Comment by mozkarakoc** [comment]
@vvscode thanks for your contribution. I'll publish a new version.
